title: Trey Dolan
email: treyrdolan@gmail.com
description: >-
  Web development student focused on building modern, user-friendly websites and applications.

  Passionate about frontend development, creative technology, electronic music, and interactive digital experiences.
baseurl: ""
url: "https://treydolan.github.io"
github_username: treydolan
linkedin_username: treydolan

theme: minima
show_excerpts: true
plugins:
  - jekyll-feed

minima:
  header_pages:
    - projects.markdown
    - work-experience.markdown
    - blog.markdown
    - about.markdown
    - contact.markdown
